feat:added the basic project structure
Assisted-Math-Learning/aml-api-service pull request #1
Opened 2024-07-30 13:31 UTC by vishwab1

Hai Team we added the basic project structure includes:
1) Packages
2)Logger 
3)Response structure
4)Postgresql
5)PostgreSQL connection

2024-07-30 13:41 UTC, vishwab1 commented
@HarishGangula Please review the Code.

2024-07-31 04:48 UTC, HarishGangula requested changes

2024-07-31 04:48 UTC, HarishGangula commented on src/app.ts
> +    app.use(bodyParser.json({ limit: '500mb' }));
You can reduce to 5mb

2024-07-31 04:48 UTC, HarishGangula commented on package.json
> +    "joi": "^17.12.3",
We will use ajv and defined JSON schema for validating the request with body

2024-07-31 04:48 UTC, HarishGangula commented on package.json
> +    "uid": "^2.0.2",
where are we using this package ?

2024-07-31 04:48 UTC, HarishGangula commented on package.json
> +    "validator": "^13.11.0",
where can we use is package ?

2024-07-31 04:48 UTC, HarishGangula commented on package.json
> +    "typeorm": "^0.3.20",
can we use  https://sequelize.org/

2024-07-31 04:48 UTC, HarishGangula commented on package.json
> +    "express": "^4.19.2",
use version 5

2024-07-31 04:48 UTC, HarishGangula commented on src/config/config.ts
> +import dotenv from 'dotenv';
dot env doesn't make sense with deployments we can use process.env this can development dependency from npm scripts

2024-07-31 04:48 UTC, HarishGangula commented on src/config/config.ts
> +const envVarsSchema: Schema = Joi.object({
keep it simple with a object instead of using JOI

2024-07-31 06:34 UTC, vishwab1 commented on package.json
> +    "express": "^4.19.2",
Currently express have  4.19.2 latest version  and 5.0.0-beta.3 in the beta version, Need your input which one is use?

2024-07-31 07:41 UTC, HarishGangula commented on package.json
> +    "express": "^4.19.2",
We can use 5.0.0-beta.3

2024-08-01 10:20 UTC, vishwab1 commented on src/app.ts
> +    app.use(bodyParser.json({ limit: '500mb' }));
Changed to the 500 mb to 5 mb.

2024-08-01 10:21 UTC, vishwab1 commented on package.json
> +    "joi": "^17.12.3",
Added the common validation in service folder.

2024-08-01 10:22 UTC, vishwab1 commented on package.json
> +    "uid": "^2.0.2",
Removed this package from the package.json

2024-08-01 10:26 UTC, vishwab1 commented on package.json
> +    "validator": "^13.11.0",
Validator package is removed from the package.json

2024-08-01 10:27 UTC, vishwab1 commented on package.json
> +    "typeorm": "^0.3.20",
Implemented the sequelize for postgres.

2024-08-01 10:28 UTC, vishwab1 commented on package.json
> +    "express": "^4.19.2",
Updated the express version to 5.0 beta version

2024-08-01 10:28 UTC, vishwab1 commented on src/config/config.ts
> +const envVarsSchema: Schema = Joi.object({
Removed the validation schema for the .env files.

2024-08-01 10:31 UTC, vishwab1 commented on src/config/config.ts
> +import dotenv from 'dotenv';
Included the script for .env file in package.json instead of dotenv.

2024-08-01 10:51 UTC, HarishGangula requested changes

2024-08-01 10:51 UTC, HarishGangula commented on package.json
> +    "joi": "^17.12.3",
joi is not removed

2024-08-01 11:43 UTC, vishwab1 commented on package.json
> +    "joi": "^17.12.3",
Removed Joi from the package.json

2024-08-01 12:09 UTC, HarishGangula approved these changes

2024-08-01 12:12 UTC, merged