feat:Added the db config, tenant api
Assisted-Math-Learning/aml-api-service pull request #10
Opened 2024-09-05 09:21 UTC by vishwab1

Database connection added
Tenant Api added
Response Structure added

2024-09-05 09:24 UTC, vishwab1 commented
@HarishGangula  Please verify the PR contain the Tenant API

2024-09-09 06:53 UTC, HarishGangula requested changes
1. Fix the spelling mistakes
2. Removed all the dependencies
3. Proper validation for the request body

2024-09-09 06:53 UTC, HarishGangula commented on package.json
> +    "@types/multer": "^1.4.12",
Remove this dependecy

2024-09-09 06:53 UTC, HarishGangula commented on package.json
>      "@types/pg": "^8.11.6",
This should go to dev dependecies

2024-09-09 06:53 UTC, HarishGangula commented on src/config/databaseConfig.ts
> +import 'reflect-metadata';
Why this package used ?

2024-09-09 06:53 UTC, HarishGangula commented on package.json
>      "reflect-metadata": "^0.2.2",
Remove this dependency

2024-09-09 06:53 UTC, HarishGangula commented on src/app.ts
> +    app.use(bodyParser.urlencoded({ limit: '5mb', extended: true, parameterLimit: 50000 }));
urlencoded used multiple times with same settings

2024-09-09 06:53 UTC, HarishGangula commented on src/app.ts
> +    process.on('uncaughtException', unexpectedErrorHandler);
`uncaughtException`, `unhandledRejection` should be outside of the method

2024-09-09 06:53 UTC, HarishGangula commented on src/config/config.ts
> +  appVersion: get(envVars, 'AML_SERVICE_APP_VERSION', '1.1'),
version should be 1.0

2024-09-09 06:53 UTC, HarishGangula commented on src/config/databaseConfig.ts
> +  models: [__dirname + '/models/*.ts'],
use path package here

2024-09-09 10:28 UTC, vishwab1 commented on package.json
> +    "@types/multer": "^1.4.12",
Removed from file

2024-09-09 10:28 UTC, vishwab1 commented on package.json
>      "@types/pg": "^8.11.6",
removed multer and pg move to dev dependencies

2024-09-09 10:28 UTC, vishwab1 commented on src/config/databaseConfig.ts
> +import 'reflect-metadata';
Removed

2024-09-09 10:28 UTC, vishwab1 commented on package.json
>      "reflect-metadata": "^0.2.2",
Removed

2024-09-09 10:29 UTC, vishwab1 commented on src/app.ts
> +    app.use(bodyParser.urlencoded({ limit: '5mb', extended: true, parameterLimit: 50000 }));
kept only express json and urlencoded

2024-09-09 10:29 UTC, vishwab1 commented on src/app.ts
> +    process.on('uncaughtException', unexpectedErrorHandler);
kept outside method

2024-09-09 10:30 UTC, vishwab1 commented on src/config/databaseConfig.ts
> +  models: [__dirname + '/models/*.ts'],
Used the Path packages

2024-09-09 10:30 UTC, vishwab1 commented on src/config/config.ts
> +  appVersion: get(envVars, 'AML_SERVICE_APP_VERSION', '1.1'),
changed to 1.0

2024-09-09 13:37 UTC, HarishGangula requested changes

2024-09-09 13:37 UTC, HarishGangula commented on src/models/tenant.ts
> +    type: {
add the allowed values in the tenant types, default of user not providing

2024-09-09 13:37 UTC, HarishGangula commented on src/utils/response.ts
> +    msgid: uuid.v4(),
this user sent msgid

2024-09-09 13:37 UTC, HarishGangula commented on src/controllers/TenantCreate/TenantCreate.ts
> +    if (dataBody.board_id && dataBody.board_id.length > 0) {
This check is not required

2024-09-09 13:37 UTC, HarishGangula commented on src/controllers/TenantCreate/TenantCreate.ts
> +  try {
Remove try catch

2024-09-09 13:37 UTC, HarishGangula commented on src/controllers/TenantCreate/TenantCreate.ts
> +      status: 'live',
move live to enum

2024-09-09 13:37 UTC, HarishGangula commented on src/controllers/TenantRead/GetSingleTenant.ts
> +    res.status(httpStatus.OK).json(successResponse(apiId, msgid, tenantDetails));
Get the clarification on `id` and `identifier`

2024-09-09 13:37 UTC, HarishGangula commented on src/services/tenant.ts
> +export const getTenantById = async (id: number): Promise<any> => {
take status as param and default it to live

2024-09-09 13:37 UTC, HarishGangula commented on src/services/tenant.ts
> +    whereClause.is_active = true;
move this line to above only

2024-09-09 13:37 UTC, HarishGangula commented on src/controllers/TenantRead/GetSingleTenant.ts
> +    const getTenantInfo = await getTenant(tenant_id);
always get live tenant which is active

2024-09-09 13:37 UTC, HarishGangula commented on src/controllers/TenantSearch/searchTenantValidationSchema.json
> +          "description": "Object containing search criteria. Can include any fields defined in the Tenant model."
add specific filters

2024-09-09 13:37 UTC, HarishGangula commented on src/controllers/TenantSearch/searchTenantValidationSchema.json
> +          "description": "Object containing search criteria. Can include any fields defined in the Tenant model."
put specific filters

2024-09-09 13:37 UTC, HarishGangula commented on src/controllers/TenantUpdate/updateTenant.ts
> +    if (dataBody.board_id && dataBody.board_id.length > 0) {
Not required

2024-09-09 13:37 UTC, HarishGangula commented on src/controllers/TenantUpdate/updateTenant.ts
> +const checkTenantExists = async (tenant_id: number): Promise<boolean> => {
Move this to service file

2024-09-09 13:37 UTC, HarishGangula commented on src/services/board.ts
> +export const getBoardsByIds = async (board_ids: number[]): Promise<any> => {
rename this to getBoards

2024-09-09 13:37 UTC, HarishGangula commented on src/services/tenant.ts
> +  const transact = await AppDataSource.transaction();
Remove transaction from all methods

2024-09-10 07:28 UTC, vishwab1 commented on src/controllers/TenantCreate/TenantCreate.ts
> +  try {
Removed added the promise method

2024-09-10 07:29 UTC, vishwab1 commented on src/controllers/TenantCreate/TenantCreate.ts
> +    if (dataBody.board_id && dataBody.board_id.length > 0) {
removed this check

2024-09-10 07:29 UTC, vishwab1 commented on src/utils/response.ts
> +    msgid: uuid.v4(),
changed msgid

2024-09-10 07:30 UTC, vishwab1 commented on src/controllers/TenantCreate/TenantCreate.ts
> +      status: 'live',
created the new folder enum and kept a file

2024-09-10 07:30 UTC, vishwab1 commented on src/controllers/TenantSearch/searchTenantValidationSchema.json
> +          "description": "Object containing search criteria. Can include any fields defined in the Tenant model."
Added the name isactive and status now

2024-09-10 07:52 UTC, vishwab1 commented on src/services/board.ts
> +export const getBoardsByIds = async (board_ids: number[]): Promise<any> => {
change to getBoards

2024-09-10 07:53 UTC, vishwab1 commented on src/services/tenant.ts
> +  const transact = await AppDataSource.transaction();
Removed

2024-09-11 05:22 UTC, HarishGangula approved these changes

2024-09-11 05:22 UTC, HarishGangula commented on src/app.ts
> +    await AppDataSource.sync()
Remove the then and catch

2024-09-11 05:22 UTC, merged