fix:removed try and catch from the app.ts
Assisted-Math-Learning/aml-api-service pull request #11
Opened 2024-09-11 05:48 UTC by vishwab1

Removed the try and catch block from app.ts

2024-09-12 08:13 UTC, Hari-1027 commented on src/models/skillMaster.ts
> +import { DataTypes } from 'sequelize';
no need skills master

2024-09-12 08:13 UTC, Hari-1027 commented on src/models/classMaster.ts
> +    name: {
name is multi lingual

2024-09-12 08:13 UTC, Hari-1027 commented on src/models/classMaster.ts
> +      type: DataTypes.STRING,
this is a array

2024-09-12 08:14 UTC, Hari-1027 commented on src/models/roleMaster.ts
> +    sequence_num: {
sequence is not needed

2024-09-12 08:14 UTC, Hari-1027 commented on src/models/subSkillMaster.ts
> +      type: DataTypes.STRING,
multilingual

2024-09-12 08:14 UTC, Hari-1027 commented on src/models/subSkillMaster.ts
> +      type: DataTypes.INTEGER,
no sequence is needed

2024-09-12 12:51 UTC, vishwab1 commented
@HarishGangula   please review the master api

2024-09-12 12:57 UTC, vishwab1 commented
[createTable.txt](https://github.com/user-attachments/files/16979582/createTable.txt)

2024-09-16 06:48 UTC, HarishGangula requested changes

2024-09-16 06:48 UTC, HarishGangula commented on src/models/boardMaster.ts
> +    class_names: {
This needs to be removed

2024-09-16 09:55 UTC, vishwab1 commented on src/models/boardMaster.ts
> +    class_names: {
@HarishGangula changes done, please verify

2024-09-17 07:10 UTC, HarishGangula approved these changes

2024-09-17 07:10 UTC, merged