skill Taxonomy API and Board, Class Update API
Assisted-Math-Learning/aml-api-service pull request #14
Opened 2024-09-25 07:59 UTC by vishwab1

1.Made all in to camel case for folder structure master api, tenant api.
2.Added the skill taxonomy data api
3. Added the update api for board, skill, class, subskill

2024-09-25 08:04 UTC, vishwab1 commented
@HarishGangula  please review the skill taxonomy api and master update api

2024-09-26 11:37 UTC, HarishGangula requested changes

2024-09-26 11:37 UTC, HarishGangula commented on src/controllers/boardUpdate/updateBoardValidationSchema.json
> +        "skill_taxonomy_ids": {
This is the single skill taxonomy id

2024-09-26 11:37 UTC, HarishGangula commented on src/controllers/boardUpdate/updateBoardValidationSchema.json
> +              "type": "array",
Add the minItems and uniqueItems and remove the condition in code

2024-09-27 04:35 UTC, vishwab1 commented on src/routes/router.ts
> +router.post('/skillTaxonomy/search', setDataToRequestObject('api.skillTaxonomy.search'), searchSkillTaxonomies);
changed

2024-09-27 05:02 UTC, vishwab1 commented on src/controllers/boardUpdate/updateBoardValidationSchema.json
> +              "type": "array",
Added the  minItems and uniqueItems

2024-09-27 07:18 UTC, HarishGangula approved these changes

2024-09-27 07:18 UTC, merged