Adding configuration to build automation using github actions
Assisted-Math-Learning/aml-api-service pull request #2
Opened 2024-08-02 11:49 UTC by Hari-1027

Adding GitHub Actions Workflow to,

- Install the dependencies
- Build the service

2024-08-02 11:50 UTC, Hari-1027 commented
@HarishGangula Kindly verify the PR

2024-08-06 11:05 UTC, HarishGangula requested changes

2024-08-06 11:05 UTC, HarishGangula commented on aml.cicd.yml
> +          context: ./command-service
copy paste issue

2024-08-06 11:05 UTC, HarishGangula commented on aml.cicd.yml
> +          tags: ${{ vars.DOCKERHUB_USERNAME }}/flink-command-service:${{ github.ref_name }}
copy paste issue

2024-08-07 05:45 UTC, Hari-1027 commented on aml.cicd.yml
> +          context: ./command-service
removed the command-service

2024-08-07 05:46 UTC, Hari-1027 commented on aml.cicd.yml
> +          tags: ${{ vars.DOCKERHUB_USERNAME }}/flink-command-service:${{ github.ref_name }}
removed the command-service

2024-08-08 05:16 UTC, HarishGangula approved these changes

2024-08-08 05:17 UTC, HarishGangula approved these changes

2024-08-08 05:17 UTC, merged