Creation of Content Api's
Assisted-Math-Learning/aml-api-service pull request #25
Opened 2024-10-03 10:36 UTC by vishwab1

Api's Includes
1. Create
2. Publish
3. Read
4. Update
5. Search
6. delete
7. discard

2024-10-04 05:00 UTC, HarishGangula requested changes
Review and fix the basic issues

2024-10-04 05:00 UTC, HarishGangula commented
Resolve the conflicts

2024-10-04 05:11 UTC, Novfal-202 commented on docs/aml_script.sql
>      process_id UUID,
During bulk operations, if the content and question set are successfully inserted but there is a validation error or issue with the question insertion, I need to roll back all previously inserted data for this particular process_id in both the staging and main tables. To facilitate this, I have added a process_id field, which is also nullable.

2024-10-05 08:26 UTC, HarishGangula approved these changes

2024-10-05 08:26 UTC, merged