fix:model correction
Assisted-Math-Learning/aml-api-service pull request #30
Opened 2024-10-09 08:40 UTC by vishwab1

This contains all model changes with declaration.

2024-10-09 10:02 UTC, HarishGangula requested changes

2024-10-09 10:02 UTC, HarishGangula commented on src/models/boardMaster.ts
> +  declare class_ids: {
This is not valid structure

It should be

```{
id: "class_1",
sequence_no: 1,
l1_skill_ids: []
}```

2024-10-09 12:04 UTC, vishwab1 commented on src/models/boardMaster.ts
> +  declare class_ids: {
@HarishGangula Resolved

2024-10-10 06:15 UTC, HarishGangula approved these changes

2024-10-10 06:15 UTC, merged